/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_notstirred_ChunkyMapView */

#ifndef _Included_io_github_notstirred_ChunkyMapView
#define _Included_io_github_notstirred_ChunkyMapView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_notstirred_ChunkyMapView_setup
  (JNIEnv *, jobject);

/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    render
 * Signature: ([Lio/github/notstirred/TilePos;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_notstirred_ChunkyMapView_render
  (JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobjectArray);

/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    getViewX
 * Signature: ()I
 */
JNIEXPORT jfloat JNICALL Java_io_github_notstirred_ChunkyMapView_getViewX
  (JNIEnv *, jobject);

/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    getViewZ
 * Signature: ()I
 */
JNIEXPORT jfloat JNICALL Java_io_github_notstirred_ChunkyMapView_getViewZ
  (JNIEnv *, jobject);

/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    getViewX
 * Signature: ()I
 */
JNIEXPORT jfloat JNICALL Java_io_github_notstirred_ChunkyMapView_getViewSizeX
  (JNIEnv *, jobject);

/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    getViewZ
 * Signature: ()I
 */
JNIEXPORT jfloat JNICALL Java_io_github_notstirred_ChunkyMapView_getViewSizeZ
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
