/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_notstirred_ChunkyMapView */

#ifndef _Included_io_github_notstirred_ChunkyMapView
#define _Included_io_github_notstirred_ChunkyMapView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    setup
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_github_notstirred_ChunkyMapView_setup
  (JNIEnv *, jobject);

/*
 * Class:     io_github_notstirred_ChunkyMapView
 * Method:    render
 * Signature: ([Lio/github/notstirred/Plane;)Z
 */
JNIEXPORT jboolean JNICALL Java_io_github_notstirred_ChunkyMapView_render
(JNIEnv *, jobject, jfloat, jfloat, jfloat, jfloat, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
